name: module3_task0

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

jobs:
  run-test:
    name: Tests the help command of the Makefile
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run make help
        run: cd module3_task0/ && make help
