name: module3_task1

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

jobs:
  run-test:
    name: Tests the help command of the Makefile
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        run: cd module3_task1/ && sudo ./setup.sh
      - name: Build
        run: cd module3_task1/ && make build
      - name: Help command
	run: cd module3_task1/ && make help
      - name: Create post
	run: cd module3_task1/ && make POST_NAME=testing POST_TITLE=Test post
      - name: Clean command
	run: cd module3_task1/ && make clean
      - name: Specific help command
	run: cd module3_task1/ && make help clean
