---
name: module3_task2

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  run-test:
    name: CD
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./module3_task2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        run: sudo ./setup.sh
      - name: Build
        run: make build
      - name: Help command
        run: make help
      - name: Create post
        run: make POST_NAME=testing POST_TITLE=Test post
      - name: Creates a package
        run: make package
      - name: Runs unit tests
        run: make unit-tests
      - name: Runs integration tests
        run: make integration-tests
      - name: Runs the validation
        run: make validate
      - name: Clean command
        run: make clean
      - name: Linting
        run: make lint
      - name: Save workflow
        uses: actions/upload-artifact@v3
        with:
          name: artifact-task2
          path: module3_task2/
